### PR TITLE
🚀 5.1.0

### LINKED ISSUE #263: A way to use physical buttons
I'm currently trying to make build an enclosure for my MK3s which also utilizes physical buttons for power etc. . Since the option of using physical buttons isn't integrated into OctoRelay I use the Physical Buttons add-on to execute Gcode-commands which then are picked up by Octorelay and then executed by the relais. This seemed to work fine until I noticed that apparently Octoprint doesn't just turn off the Gcode terminal when no printer is connected, it also disables the ability to execute Gcode commands from every other source, which is kindof problematic if I want to use this for a power button that turns off the printer but keeps running.

Long story short: it would be great if either inputs could be directly processed by octorelay or if there would be a simple way to use what physical buttons calls system commands. Some other solution to this is also fine with me

### LINKED ISSUE #299: Physical Button Plugin broken
Plugin Version
5.0.1

Question
So far I have used "Physical Button"a GPIO Input via Hardware Button to toggle the light ( =>Action: GPIO toggle).

The output is also used by the Octorelay plug-in to control the light. This worked well for a long time. Unfortunately, the button no longer reacts as long as the Octo Relay plug-in is running. Without the Octorelay plug-in, everything works perfectly!
I also tried the Workaround with GCODE in Physical Button, but also this does not work.

Is this a topic for here, or for Physicl Button?

Additional context
Physical Button Version 0.6.2

### PR DESCRIPTION
**Pull request by RobinTail**
Fixes #263 
Fixes #299 

- #320 
- #322 
- #315

### CODE REVIEW

**Comment by RobinTail** [comment]
🚀 5.1.0rc1

**Comment by RobinTail** [comment]
🚀 5.1.0rc2
✅ fixes issue for PhysicalButton plugin, able to operate relay in both plugins

**Comment by RobinTail** [comment]
Dear @ch3p4ll3 ,

could you please try version 5.1.0rc2 on Raspberry Pi 5 and check:
- there are no errors in log and you're still able to operate relays

Dear @ccle610 ,

could you please try version 5.1.0rc2 on Raspberry Pi 5 and check:
- there are no errors in log and you can operate a relay in both plugins, having `output` action in your PhysicalButton plugin having similar config:

image

**Comment by ccle610** [comment]
Hi RobinTail,
I'm still happy with solution #263, using System Command Action for that purpose, using curl command to ask OctoRelay to do the job, version 5.1.0rc2 is running on Raspberry Pi 4.
But I can test it out, when back home again . . .

**Comment by RobinTail** [comment]
> But I can test it out, when back home again . . .

Yes, please. No rush, take your time, @ccle610

**Comment by RobinTail** [comment]
Dear @ccle610 , did you have a chance to get home? :)

**Comment by ccle610** [comment]
Hi Anna, sorry for the delay, i did not find the time during the week . . . but I've checked out what happens, when GPIO Toggle is used once again on my Octoprint 1.10.1 running OctoPi 1.0.0 atRaspi 4: Nothing ;-(
Only the Workaround through OctoRelais still is working fine (what is ok for me!)

Regards, haJue
[button_config_25-1-2023_15-39-23.json](https://github.com/user-attachments/files/17530191/button_config_25-1-2023_15-39-23.json)
[button_config_26-10-2024_12-48-55.json](https://github.com/user-attachments/files/17530192/button_config_26-10-2024_12-48-55.json)

**Comment by RobinTail** [comment]
> on my Octoprint 1.10.1 running OctoPi 1.0.0 atRaspi 4: Nothing ;-(

hmmm... it's strange that it works in my case for some reason...

**Comment by ccle610** [comment]
Okay. Let me double check GPIO Pins etc.
But for now, I'm printing . . . not a good idea, to play around in settings . . . maybe tomorrow. HaJue

**Comment by ccle610** [comment]
Hi there once again,
after reconfiguring all that stuff in Octorelais and Pysical Button Plugin a GPIO output action does only work, when it is not configured in Octo Relais 5.0.3
Workaround still works fine . . . 

Sorry, having no better news today!
But I'm realy happy with this Plugin and the solution, it is perfect for my setup.
For me, nothing needs to be changed at all ;-)
HaJue

**Comment by ccle610** [comment]
Hi Anna, have to say sorry!
My mistake . . . in background the Octo relais Plugin was automatical "updated" to Ver, 5.0.3 and I did not recognized that.
Now I have tested once again with 5.1.0RC2 and voila - Physical Button is working with Action "toggle GPIO" like in those good old days . 
Great Job, HaJue

By the way, I have understood what I did wrong:
When I've started printig today, I was a litte in a hurry and so the Button "Update all" was pushed ;-(

Octoprint now comes up with an update message:
Aktualisierung verfügbar
Es gibt Aktualisierungen für die folgenden Komponenten:

    OctoRelay: 5.0.3[Release Notes](https://github.com/borisbu/OctoRelay/releases/tag/5.0.3)

**Comment by RobinTail** [comment]
> Physical Button is working with Action "toggle GPIO" like in those good old days .

Perfect! Thank you so much for testing, @ccle610 
I'm super glad!

> Octoprint now comes up with an update message:
>> Aktualisierung verfügbar
>> Es gibt Aktualisierungen für die folgenden Komponenten:

Yes, this is normal.
When I merge this PR and publish 5.1.0 (without `rc`) it will become latest and will no longer offer you downgrade.

**Review by RobinTail — COMMENTED** [review]
ready

**Pull request merged**
